### ISSUE TITLE
Discover the real source of data

### ISSUE THREAD

**Issue by gregmedlock** [databio/bds_hackathon#2]
We need to identify metadata/how data was generated for the files that accompany the paper:

Supplementary file | Size | Download | File type/resource
-- | -- | -- | --
GSE100866_CBMC_8K_13AB_10X-ADT_clr-transformed.csv.gz | 945.1 Kb | (ftp)(http) | CSV
GSE100866_CBMC_8K_13AB_10X-ADT_umi.csv.gz | 189.8 Kb | (ftp)(http) | CSV
GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv.gz | 14.2 Mb | (ftp)(http) | CSV
GSE100866_CD8_merged-ADT_clr-transformed.csv.gz | 58.4 Kb | (ftp)(http) | CSV
GSE100866_CD8_merged-ADT_umi.csv.gz | 19.3 Kb | (ftp)(http) | CSV
GSE100866_CD8_merged-RNA_umi.csv.gz | 1.4 Mb | (ftp)(http) | CSV
GSE100866_PBMC_vs_flow_10X-ADT_clr-transformed.csv.gz | 466.9 Kb | (ftp)(http) | CSV
GSE100866_PBMC_vs_flow_10X-ADT_umi.csv.gz | 129.4 Kb | (ftp)(http) | CSV
GSE100866_PBMC_vs_flow_10X-RNA_umi.csv.gz | 10.1 Mb | (ftp)(http) | CSV
SRP/SRP111/SRP111194 |   | (ftp) | SRA Study

For each of these files, we should describe which experiment they came from, the number of groups involved in the experiment, the number of features (genes).

**Comment by nsheff** [comment]
FYI, I have downloaded all these processed files into `/sfs/lustre/allocations/bds_tg/citeseq`

Is anyone planning to look at the raw data?

**Comment by gregmedlock** [comment]
We briefly discussed the possibility of experimenting the raw data, but I think it is low priority because of the potentially hefty computing power/time required.
